autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin()
Plug 'devsjc/vim-jb'
call plug#end()

colorscheme jb
filetype plugin indent on
syntax on
set autoindent
set backspace=indent,eol,start
set incsearch
set ruler
set wildmenu
set hidden
set tabstop=4
set shiftwidth=4
set expandtab
